# Generated by Django 4.2.2 on 2025-04-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_routeexclusion_required_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anemometer', models.IntegerField(default=1)),
                ('rainfall', models.IntegerField(default=1)),
                ('humidity', models.IntegerField(default=1)),
            ],
        ),
    ]
